import React, { useRef } from "react";
import TopComponent from "./TopComponent";
import AboutUs from "./AboutUs";
import WhyUs from "./WhyUs";
import Testimonials from "./Testimonials";
import Navbar from "./Navbar";
import MissionVision from "./VisionMission";

const NeetPG = () => {
  const aboutUsRef = useRef(null);
  const whyUsRef = useRef(null);
  const testimonialsRef = useRef(null);
  const refs = {
    aboutUsRef,
    whyUsRef,
    testimonialsRef,
  };

  const scrollToSection = (section) => {
    if (refs[section]?.current) {
      refs[section].current.scrollIntoView({ behavior: "smooth" });
    }
  };

  return (
    <div className="min-h-screen bg-blue-950">
      <Navbar scrollToSection={scrollToSection} />
      <TopComponent />
      <div className=" mx-auto px-4 space-y-24 py-24 ">
        <section ref={aboutUsRef} id="about-us" className="border-2 rounded-xl border-white  p-4">
          <AboutUs />
        </section>

        <section className="border-2 rounded-xl border-white  p-4">
          <MissionVision />
        </section>

        <section ref={whyUsRef} id="why-us" className="border-2 rounded-xl border-white p-4">
          <WhyUs />
        </section>
        <section ref={testimonialsRef} id="testimonials" className="border-2 rounded-xl border-white p-4">
          <Testimonials />
        </section>
      </div>
    </div>
  );
};

export default NeetPG;

// Below is the code of a slightly improved UI generated by v0 

// import React, { useRef } from "react";
// import { motion } from "framer-motion";
// import TopComponent from "./TopComponent";
// import AboutUs from "./AboutUs";
// import WhyUs from "./WhyUs";
// import Testimonials from "./Testimonials";
// import Navbar from "./Navbar";

// const NeetPG = () => {
//   const aboutUsRef = useRef(null);
//   const whyUsRef = useRef(null);
//   const testimonialsRef = useRef(null);
//   const refs = {
//     aboutUsRef,
//     whyUsRef,
//     testimonialsRef,
//   };

//   const scrollToSection = (section) => {
//     if (refs[section]?.current) {
//       refs[section].current.scrollIntoView({ behavior: "smooth" });
//     }
//   };

//   const sectionVariants = {
//     hidden: { opacity: 0, y: 20 },
//     visible: { 
//       opacity: 1, 
//       y: 0,
//       transition: { duration: 0.6 }
//     }
//   };

//   return (
//     <div className="min-h-screen bg-blue-950 text-white overflow-hidden">
//       <div className="fixed inset-0 bg-gradient-to-br from-blue-900 to-blue-950 z-[-1]" />
//       <Navbar scrollToSection={scrollToSection} />
//       <TopComponent />
//       <div className="max-w-7xl mx-auto px-4 py-24 space-y-32">
//         <motion.section
//           ref={aboutUsRef}
//           id="about-us"
//           className="relative backdrop-blur-sm bg-white/5 rounded-2xl p-8 shadow-xl"
//           variants={sectionVariants}
//           initial="hidden"
//           whileInView="visible"
//           viewport={{ once: true }}
//         >
//           <div className="absolute inset-0 bg-gradient-to-r from-blue-500/10 to-purple-500/10 rounded-2xl z-[-1]" />
//           <AboutUs />
//         </motion.section>

//         <motion.section
//           ref={whyUsRef}
//           id="why-us"
//           className="relative backdrop-blur-sm bg-white/5 rounded-2xl p-8 shadow-xl"
//           variants={sectionVariants}
//           initial="hidden"
//           whileInView="visible"
//           viewport={{ once: true }}
//         >
//           <div className="absolute inset-0 bg-gradient-to-r from-yellow-500/10 to-red-500/10 rounded-2xl z-[-1]" />
//           <WhyUs />
//         </motion.section>

//         <motion.section
//           ref={testimonialsRef}
//           id="testimonials"
//           className="relative backdrop-blur-sm bg-white/5 rounded-2xl p-8 shadow-xl"
//           variants={sectionVariants}
//           initial="hidden"
//           whileInView="visible"
//           viewport={{ once: true }}
//         >
//           <div className="absolute inset-0 bg-gradient-to-r from-green-500/10 to-teal-500/10 rounded-2xl z-[-1]" />
//           <Testimonials />
//         </motion.section>
//       </div>
//     </div>
//   );
// };

// export default NeetPG;


